/**
 * This file was generated by the Jeddict
 */
package entity;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
@NamedQueries({
    @NamedQuery(name = "Account.findByUsername", query = "Select e from Account e where e.username=:username")
    ,@NamedQuery(name = "Account.findByPassword", query = "Select e from Account e where e.password=:password")
    ,@NamedQuery(name = "Account.Connect", query = "Select e from Account e WHERE e.password = :password AND e.username = :username")})
public class Account {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(unique = true, nullable = false)
    @Basic(optional = false)
    @Size(min = 5, max = 30, message = "votre nom d'utilisateur dois etre compris en 5 et 30 caractÃƒÆ’Ã‚Â¨re")
    @NotNull(message = "Veuillez saisir un nom d utilisateur")
    private String username;

    @Column(nullable = false)
    @Basic(optional = false)
    @Size(min = 6, max = 30, message = "votre mot de passe doit etre compris entre 6 et 30 caractere")
    @NotNull(message = "veuillez saisir le mot de passe")
    private String password;

    
    @OneToOne(targetEntity = UserInfo.class)
    private UserInfo userInfo;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public UserInfo getUserInfo() {
        return this.userInfo;
    }

    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

}